# Generated by Django 4.0.dev20210219192511 on 2021-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
