# Generated by Django 4.0.dev20210219192511 on 2021-04-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0002_alter_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='song_file',
            fields=[
                ('song_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('song_name', models.CharField(max_length=100)),
                ('song_upload', models.FileField(upload_to='media')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True, verbose_name='Track duration ins seconds')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
