# Generated by Django 4.0.dev20210219192511 on 2021-04-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0005_alter_song_file_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_file',
            name='duration_seconds',
            field=models.PositiveIntegerField(null=True, verbose_name='Track duration ins seconds'),
        ),
    ]
