# Generated by Django 4.0.dev20210219192511 on 2021-04-11 11:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0006_alter_song_file_duration_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 17, 29, 12, 81906)),
        ),
    ]
