# Generated by Django 4.0.dev20210219192511 on 2021-04-11 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0007_alter_song_file_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_file',
            name='duration_seconds',
            field=models.PositiveIntegerField(verbose_name='Track duration ins seconds'),
        ),
        migrations.AlterField(
            model_name='song_file',
            name='song_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song_file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 10, 12, 925196)),
        ),
    ]
