# Generated by Django 4.0.dev20210219192511 on 2021-04-11 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0008_auto_20210411_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_file',
            name='duration_seconds',
            field=models.DurationField(verbose_name='Track duration ins seconds'),
        ),
        migrations.AlterField(
            model_name='song_file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 16, 57, 953971)),
        ),
    ]
