# Generated by Django 4.0.dev20210219192511 on 2021-04-11 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0011_alter_song_file_upload_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='song_file',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=23, verbose_name='Track duration ins seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='song_file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 24, 30, 977807)),
        ),
    ]
