# Generated by Django 4.0.dev20210219192511 on 2021-04-11 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_task', '0012_auto_20210411_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_file',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 20, 25, 20, 640922)),
        ),
    ]
